Feature/initial config
baobabsoluciones/frontend-config pull request #1
Opened 2024-10-09 14:44 UTC by HelenaCA

2024-10-10 14:21 UTC, ggsdc commented
Is this ready for review/merge?

2024-10-10 14:32 UTC, HelenaCA commented
> Is this ready for review/merge?

Yes

2024-10-10 14:41 UTC, ggsdc requested changes

2024-10-10 14:41 UTC, ggsdc commented on .gitignore copy
can we delete this one?

2024-10-10 14:41 UTC, ggsdc commented on public/vite.svg
Do we need this file?

2024-10-10 14:41 UTC, ggsdc commented on src/assets/styles/main.css
Is that many `!important` needed? I always thought that `!important` was something to use rarely

2024-10-10 14:41 UTC, ggsdc commented on src/assets/vue.svg
Is this file needed?

2024-10-10 14:44 UTC, HelenaCA commented on src/assets/styles/main.css
Yes, it is because it's overriding some already declared classes from vuetify, but normally it's not needed. 
But thank you for pointing it as there are some classes that I will not add here, so I'll change it

2024-10-24 13:37 UTC, HelenaCA commented
@ggsdc Ready for merge

2024-10-24 15:37 UTC, ggsdc approved these changes

2024-10-24 15:37 UTC, merged